/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "teste.h"

int *
soma_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (*argp).x + (*argp).z;
	return &result;
}

int *
subtracao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (*argp).x - (*argp).z;
	return &result;
}

int *
divisao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (*argp).x / (*argp).z;
	return &result;
}

int *
multiplicacao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (*argp).x * (*argp).z;
	return &result;
}

int *
maior_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	if ((*argp).x > (*argp).z){
		result = (*argp).x;
	} else {
		result = (*argp).z;	
	}

	return &result;
}

int *
exponenciacao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
menor_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
